details:
  name: Full Stack Web Development
  repository_name: unit-full-stack-web-development

sequence:
  Servers:
    - name: Unit 4 Launch
      elements:
        - kind: deck
        - kind: recording
    - name: Bootstrap CSS
      pursuit_path: bootstrap-css
      kind: lesson
      activity: ~
    ########### NEEDS ATTENTION ############
    - name: Install PostgreSQL
      elements:
        - kind: guide
          pursuit_path: computer-setup
        - kind: recording
    #######################################
    - name: Intro to the Internet and Servers
      pursuit_path: intro-to-internet-and-servers
      kind: lesson
      activity: ~
    - name: Introduction to Express Response
      pursuit_path: intro-to-express-response
      kind: lesson
      activity: repository
    - name: Introduction to Express Request
      pursuit_path: intro-to-express-request
      kind: lesson
      activity: repository
    - name: Express CRUD/MVC - Index
      pursuit_path: express-rest-crud-mvc-index
      kind: lesson
      activity: repository
    - name: Express Middleware & RESTful Routes - Show & Create
      pursuit_path: express-rest-show-create
      kind: lesson
      activity: repository
    - name: Express RESTful Routes - Delete & Update
      pursuit_path: express-rest-delete-show
      kind: lesson
      activity: ~ # continue previous lab
    - name: Connect Express & Front-end Framework Connection - Cors & Index
      pursuit_path: express-connect-react
      kind: lesson
      activity: repository
    - name: Connect Express & Front-end Framework - Show, Delete, & Update
      pursuit_path: express-connect-react
      kind: lesson
      activity: ~ # continue previous lab
    - name: Budgeting App
      pursuit_path: budgeting-app
      kind: project
      activity: repository
      points_possible: 10
    - name: Server Deployment
      pursuit_path: server-deployment
      kind: lesson
    ########### NEEDS ATTENTION ############
    - name: Server Deployment
      elements:
        - kind: guide
          pursuit_path: guide-deployment
        - kind: recording
    #######################################
  Databases:
    - name: Intro to Databases & SQL
      pursuit_path: intro-to-sql
      kind: lesson
      activity: repository
    - name: App Planning ERDs
      pursuit_path: app-planning-erds
      kind: lesson
      activity: repository
    - name: SQL Joins
      pursuit_path: intro-to-sql-joins
      kind: lesson
      activity: repository
  Full Stack:
    - name: Express & SQL - Seed & Read
      pursuit_path: express-sql-seed-read
      kind: lesson
      activity: repository
    - name: Express & SQL - Create & Show
      pursuit_path: express-sql-create-show
      kind: lesson
      activity: ~ # continue previous lab
    - name: Express & SQL - Delete & Update
      pursuit_path: express-sql-delete-update
      kind: lesson
      activity: ~ # continue previous lab
    - name: PERN Stack
      pursuit_path: pern-crud
      kind: lesson
      ########### NEEDS ATTENTION ############
      # Students should submit their backend as a lab
      # This is a monorepo, so the next thing they will do is the front-end
      # They should submit the front-end as a separate lab, even though it is in the same repo
      # Finally, they should submit their attempt at one to many as a third lab
      # The challenge is that the pursuit path changes for lesson to lesson
      # But the pursuit path should stay the same for the lab(s)
      # Right now, when there is a two day lab but one submission I just mark the activity as null
      # But in this case there are repeated submissions on the same repo
      #######################################
      activity: ~ # continue previous lab
    - name: PERN Stack - One to Many Back-End
      pursuit_path: pern-one-to-many-back-end
      kind: lesson
      activity: ~ # continue previous lab
    - name: PERN Stack - One to Many Front-End
      pursuit_path: pern-one-to-many-front-end
      activity: ~ # continue previous lab
    - name: PERN BONUS Topic
      pursuit_path: pern-many-to-many
      kind: lesson
      activity: repository
    - name: PERN BONUS Topic
      pursuit_path: pern-many-to-many
      kind: lesson
      activity: ~ # Continue last lab
    - name: App Planning - Trello
      pursuit_path: app-planning-trello
      kind: lesson
      activity: repository
    - name: App Planning - Wireframes
      pursuit_path: app-planning-wireframes
      kind: lesson
      activity: repository
    - name: Snack-a-Log Pair Project
      pursuit_path: snack-a-log
      kind: project
      activity: repository
    - name: Full-Stack Portfolio Project
      pursuit_path: full-stack-portfolio
      kind: project
      activity: repository
    - name: End of Module Reflection
      elements:
        - kind: deck
        - kind: recording
